CREATE TABLE PRICES (
    ID LONG NOT NULL PRIMARY KEY,
    BRAND_ID LONG NOT NULL,
    START_DATE DATETIME NOT NULL,
    END_DATE DATETIME NOT NULL,
    PRICE_LIST LONG NOT NULL,
    PRODUCT_ID LONG NOT NULL,
    PRIORITY INT NOT NULL,
    PRICE FLOAT NOT NULL,
    CURR VARCHAR(10) NOT NULL
);